services:

  postgres:
    image: postgres:15

    environment:
      POSTGRES_DB: smart_retail_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - postgres

  frontend:
    build: ./frontend

    ports:
      - "3000:3000"

    volumes:
      - ./frontend:/app

    stdin_open: true

    depends_on:
      - backend

volumes:
  postgres_data: